# Generated by Django 5.2.6 on 2025-11-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=128)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_nasc', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_cuidadores/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pfi.usuario')),
                ('necessidade', models.TextField()),
                ('turno_preferencia', models.CharField()),
            ],
            bases=('pfi.usuario',),
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pfi.usuario')),
                ('formacao', models.CharField(blank=True, max_length=200, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=200, null=True)),
                ('experiencia', models.IntegerField(blank=True, null=True)),
                ('disponibilidade', models.CharField(blank=True, max_length=200, null=True)),
                ('cidades', models.ManyToManyField(blank=True, related_name='cuidadores', to='pfi.cidade')),
            ],
            bases=('pfi.usuario',),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('turno', models.CharField(max_length=100)),
                ('horario_inicial', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('observacao', models.TextField()),
                ('descricao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.cliente')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=100)),
                ('data_msg', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.solicitacao')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao_Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('comentario', models.TextField()),
                ('data_avalicao', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.solicitacao')),
                ('cliente_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.cliente')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('comentario', models.TextField()),
                ('data_avalicao', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.solicitacao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.cliente')),
                ('cuidador_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfi.cuidador')),
            ],
        ),
    ]
