# Generated by Django 5.2.6 on 2025-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
