# Generated by Django 5.2.6 on 2025-11-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfi', '0002_remove_usuario_endereco_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='disponibilidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='formacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
