# Generated by Django 5.2.6 on 2025-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfi', '0003_alter_cuidador_disponibilidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='cidades',
            field=models.ManyToManyField(blank=True, related_name='cuidadores', to='pfi.cidade'),
        ),
    ]
